GET http://localhost:3000/cursos/programacion/

###

PUT http://localhost:3000/cursos/programacion 

###

POST http://localhost:3000/cursos/programacion 
content-type: application/json;
{
    'id': 4,
    'titulo': 'Go'
}